### ISSUE TITLE
resized images cause 404 error.. rooibos.storage.views._add_header?

### ISSUE THREAD

**Issue by hanleybrand** [hanleybrand/rooibos#6]
It looks like something is breaking some of the media retrieval urls, but I'm not sure what it is. 

Obviously the localhost links won't actually work, but here's what it looks like on my machine

Browser makes a request to http://127.0.0.1:8000/media/get/49/xir208568/640x480/ for a preview image displayed in page

rooibos.log:

```
[19/Aug/2015 15:29:25]"GET /data/record/49/xir208568/ HTTP/1.1" 200 711834
DEBUG Updating user object with cached IP based groups ()
DEBUG get_image: /Users/hanley/dev/mdid-data/hacking-mdid3/store/xir208568.jpg (image/jpeg)
[19/Aug/2015 15:29:26]"GET /media/get/49/xir208568/640x480/ HTTP/1.1" 404 453496
DEBUG Updating user object with cached IP based groups ()
DEBUG get_image: /Users/hanley/dev/mdid-data/hacking-mdid3/store/xir208568.jpg (image/jpeg)
[19/Aug/2015 15:30:31]"GET /media/get/49/xir208568/640x480/ HTTP/1.1" 404 453436
```

browser result:

> Page not found (404)
> Request Method:	GET
> Request URL:	http://127.0.0.1:8000/media/get/49/xir208568/640x480/
> **Raised by:	rooibos.storage.views._add_header**

BUT 
* the link from the admin interface (admin/rooibos/media/10/  [/admin/r/68/10/](http://127.0.0.1:8000/admin/r/68/10/) and 
* the media link from the record page http://127.0.0.1:8000/media/get/49/xir208568/10/xir208568/ 

both work...

**Comment by knabar** [comment]
What revision are you on for this error?  I remember a bug with adding the content length header, but thought I fixed it somewhere...

**Comment by hanleybrand** [comment]
storage/views.py:46
<function retrieve_image at 0x106b16cf8>
kwargs: {'recordid': u'49', 'record': u'xir208568', 'height': u'480', 'width': u'640'}
Presentation = {ModelBase} <class 'rooibos.presentation.models.Presentation'>
passwords = {dict} {}
record = {Record} xir208568
record_id = {unicode} u'49'
user = {SimpleLazyObject} User: hanley

filter_by_access step:
manage = {bool} False
queryset = {QuerySet} [<Storage: store>]
read = {bool} True
user = {SimpleLazyObject} User: hanley
write = {bool} False

get_image_for_record step
crop_to_square = {bool} False
height = {int} 480
media = {QuerySet} [<Media: xir208568.jpg>]
passwords = {dict} {}
q = {Q} (AND: ('mimetype__startswith', 'image/'))
record = {unicode} u'49'
user = {SimpleLazyObject} User: hanley
width = {int} 640

**Comment by hanleybrand** [comment]
@knabar - this is with the dj_18WAT repo https://github.com/hanleybrand/rooibos/commit/1265af3c8e8c78064b8a4c749717c8551bd87904#diff-9341edcb3c07d51cf489b48a42561f96

I'll check against the file in your fynbos repo to see if the add_header decorator is different

**Comment by hanleybrand** [comment]
sadly, I believe I have the most recent version - I'm not sure if it's the add_header function though - I'm stepping through it in the debugger now, and I started having that feeling that I know what the problem is but it's somewhere else.

**Comment by hanleybrand** [comment]
I'll chase down that StingIO lead when I get home

**Comment by hanleybrand** [comment]
I just renamed the issue because I realized it wa very misleading - full size images work, but dynamically resized images do not (e.g. get/49/xir208568/640x480/ from the description is what's not working)

**Comment by hanleybrand** [comment]
StringIO.StringIO() != io.StringIO()

**Comment by hanleybrand** [comment]
ps - it was all my fault; I had forgotten that I had added some code to see if this module would run in python3.  The answer was "no, plus the code I added made it not work in python 2 as well"
